"use client";

import { useState } from "react";

export interface CausalTriple {
  head: string;
  relationship: string;
  tail: string;
  detail: string;
}

export interface CausalItem {
  pattern_type: string;
  sentence_type: string;
  marked_type: string;
  explicit_type: string;
  marker: string | null;
  source_text: string;
  extracted: CausalTriple[];
}

export interface GeneratedQuestionsData {
  source_text: string;
  sentence_type: string;
  generated_questions: string[];
}

type FollowUpGenerationPageProps = {
  initialCausalItems?: CausalItem[];
};

const mockCausalItems: CausalItem[] = [
  {
    pattern_type: "C",
    sentence_type: "SB",
    marked_type: "U",
    explicit_type: "I",
    marker: null,
    source_text: "But it still has not solved the routing bottleneck for night collection shifts.",
    extracted: [
      {
        head: "The compact design of the cage",
        relationship: "causes",
        tail: "difficulty for the cleaners",
        detail: "because it is too small",
      },
    ],
  },
  {
    pattern_type: "C",
    sentence_type: "SP",
    marked_type: "U",
    explicit_type: "I",
    marker: null,
    source_text: "When transfer windows are reduced, truck queues become unpredictable at district hubs.",
    extracted: [
      {
        head: "Reduced transfer windows",
        relationship: "causes",
        tail: "queue instability",
        detail: "because inbound trucks overlap in short time windows",
      },
    ],
  },
  {
    pattern_type: "C",
    sentence_type: "SB",
    marked_type: "U",
    explicit_type: "I",
    marker: null,
    source_text: "Policy changes affect load balancing, but the impact conditions remain unclear.",
    extracted: [
      {
        head: "Changing the policy",
        relationship: "causes",
        tail: "changes in system state",
        detail: "through allocation rules and timing constraints",
      },
    ],
  },
];

function GoogleGIcon() {
  return (
    <svg aria-hidden="true" className="h-5 w-5" viewBox="0 0 18 18">
      <path
        d="M17.64 9.2c0-.64-.06-1.25-.17-1.84H9v3.48h4.84a4.1 4.1 0 0 1-1.79 2.69v2.23h2.9c1.69-1.55 2.69-3.83 2.69-6.56Z"
        fill="#4285F4"
      />
      <path
        d="M9 18c2.43 0 4.47-.8 5.95-2.17l-2.9-2.23c-.8.54-1.82.86-3.05.86-2.35 0-4.34-1.58-5.06-3.71H.95v2.3A9 9 0 0 0 9 18Z"
        fill="#34A853"
      />
      <path
        d="M3.94 10.75a5.39 5.39 0 0 1 0-3.5v-2.3H.95a9 9 0 0 0 0 8.1l2.99-2.3Z"
        fill="#FBBC05"
      />
      <path
        d="M9 3.58c1.32 0 2.51.45 3.44 1.34l2.58-2.58C13.47.89 11.43 0 9 0A9 9 0 0 0 .95 4.95l2.99 2.3C4.66 5.16 6.65 3.58 9 3.58Z"
        fill="#EA4335"
      />
    </svg>
  );
}

function CausalCard({ causal }: { causal: CausalItem }) {
  const extracted = causal.extracted[0];

  return (
    <article className="min-h-44 rounded-xl border border-neutral-700 bg-neutral-900/80 p-4">
      <p className="mb-3 rounded-lg border border-neutral-700 bg-neutral-950/90 p-3 text-sm text-neutral-200">
        {causal.source_text}
      </p>

      {extracted ? (
        <div className="space-y-1 text-xs text-neutral-300">
          <p>
            <span className="font-semibold text-neutral-100">Head:</span> {extracted.head}
          </p>
          <p>
            <span className="font-semibold text-neutral-100">Relation:</span> {extracted.relationship}
          </p>
          <p>
            <span className="font-semibold text-neutral-100">Tail:</span> {extracted.tail}
          </p>
          <p>
            <span className="font-semibold text-neutral-100">Detail:</span> {extracted.detail}
          </p>
        </div>
      ) : null}
    </article>
  );
}

function GeneratedResultCard({ result }: { result: GeneratedQuestionsData }) {
  return (
    <article className="relative min-h-40 rounded-xl border border-sky-700/40 bg-neutral-900/85 p-4">
      <p className="text-xs font-semibold uppercase tracking-wide text-sky-300">
        {result.sentence_type} | Generated Questions
      </p>
      <p className="mt-2 text-xs text-neutral-400">Source: {result.source_text}</p>

      <div className="mt-3 space-y-2 pr-7">
        {result.generated_questions.map((question) => (
          <p key={question} className="rounded-lg border border-neutral-700 bg-neutral-950/90 p-2 text-sm text-neutral-100">
            {question}
          </p>
        ))}
      </div>

      <span className="absolute bottom-3 right-3 text-neutral-300" title="Generated by Google model">
        <GoogleGIcon />
      </span>
    </article>
  );
}

async function buildMockGeneratedResults(selectedItems: CausalItem[]): Promise<GeneratedQuestionsData[]> {
  await new Promise((resolve) => setTimeout(resolve, 900));

  return selectedItems.map((item) => {
    const focusEntity = item.extracted[0]?.head ?? "this factor";
    const targetEntity = item.extracted[0]?.tail ?? "the system state";

    return {
      source_text: item.source_text,
      sentence_type: "SP",
      generated_questions: [
        `How exactly does ${focusEntity} lead to improvements in ${targetEntity} within the simulation?`,
        `What specific assumptions are made when predicting how ${focusEntity} affects ${targetEntity}?`,
      ],
    };
  });
}

export default function FollowUpGenerationPage({ initialCausalItems = mockCausalItems }: FollowUpGenerationPageProps) {
  const [selectedCausals, setSelectedCausals] = useState<Set<number>>(() => new Set());
  const [generatedResults, setGeneratedResults] = useState<GeneratedQuestionsData[]>([]);
  const [hasGenerated, setHasGenerated] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isFiltering, setIsFiltering] = useState(false);

  const toggleSelection = (index: number) => {
    setSelectedCausals((previous) => {
      const next = new Set(previous);
      if (next.has(index)) {
        next.delete(index);
      } else {
        next.add(index);
      }
      return next;
    });
  };

  const handleGenerateQuestions = async () => {
    setIsGenerating(true);

    const selectedItems = initialCausalItems.filter((_, index) => selectedCausals.has(index));
    const results = await buildMockGeneratedResults(selectedItems);

    setGeneratedResults(results);
    setHasGenerated(true);
    setIsGenerating(false);
  };

  const handleRunFilter = async () => {
    if (!hasGenerated || generatedResults.length === 0) {
      return;
    }

    setIsFiltering(true);
    await new Promise((resolve) => setTimeout(resolve, 650));

    const filtered = generatedResults.map((result) => {
      const keptQuestions = result.generated_questions.filter((question) =>
        /(simulation|system|policy|state|assumption|predict)/i.test(question),
      );

      return {
        ...result,
        generated_questions: keptQuestions.length > 0 ? keptQuestions : result.generated_questions.slice(0, 1),
      };
    });

    setGeneratedResults(filtered);
    setIsFiltering(false);
  };

  return (
    <section className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-4 backdrop-blur-sm md:p-6">
      <header className="mx-auto mb-6 max-w-3xl text-center">
        <h2 className="text-xl font-bold text-neutral-100 md:text-2xl">Follow-up question section</h2>
        <p className="mt-2 text-sm text-neutral-300">
          You can generate follow-up questions for implicit information based on your input, and the engine will
          generate analytical questions for you to obtain more useful information and accuracy. (This part is optional)
        </p>
      </header>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_120px_minmax(0,1fr)]">
        <div>
          <p className="mb-3 text-sm font-semibold text-neutral-200">Select implicit causal for question generation</p>
          <div className="space-y-3">
            {initialCausalItems.map((causal) => (
              <CausalCard key={causal.source_text} causal={causal} />
            ))}
          </div>
        </div>

        <div>
          <p className="mb-3 text-sm font-semibold text-neutral-200">Action</p>
          <div className="space-y-3">
            {initialCausalItems.map((causal, index) => {
              const isSelected = selectedCausals.has(index);

              return (
                <div key={`${causal.source_text}-choose`} className="flex min-h-44 items-center justify-center">
                  <button
                    type="button"
                    onClick={() => toggleSelection(index)}
                    aria-pressed={isSelected}
                    className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold transition ${
                      isSelected
                        ? "border-sky-500 bg-sky-500/20 text-sky-200"
                        : "border-neutral-700 bg-neutral-800 text-neutral-200 hover:border-neutral-500"
                    }`}
                  >
                    <span>Choose</span>
                    <span className="inline-flex h-4 w-4 items-center justify-center rounded-full border border-current text-xs leading-none">
                      x
                    </span>
                  </button>
                </div>
              );
            })}
          </div>
        </div>

        <div>
          <p className="mb-3 text-sm font-semibold text-neutral-200">Generated output</p>
          <div className="flex flex-col gap-3 lg:flex-row lg:items-start">
            <div className="flex-1 space-y-3">
              {!hasGenerated ? (
                <div className="rounded-xl border border-dashed border-neutral-700 bg-neutral-900/70 p-6 text-sm text-neutral-400">
                  Generated questions will appear here after clicking Generate questions.
                </div>
              ) : null}

              {hasGenerated && generatedResults.length === 0 ? (
                <div className="rounded-xl border border-dashed border-amber-600/40 bg-amber-950/20 p-6 text-sm text-amber-200">
                  No causal item selected. Choose one or more causals first, then generate questions.
                </div>
              ) : null}

              {generatedResults.map((result) => (
                <GeneratedResultCard key={result.source_text} result={result} />
              ))}
            </div>

            <aside className="w-full rounded-xl border border-neutral-700 bg-neutral-900/70 p-3 lg:w-40">
              <p className="text-xs text-neutral-300">
                filter out questions that can be answered from the internet
              </p>
              <button
                type="button"
                onClick={handleRunFilter}
                disabled={isFiltering || !hasGenerated || generatedResults.length === 0}
                className="mt-3 w-full rounded-lg border border-sky-500 bg-sky-500/20 px-3 py-2 text-sm font-bold text-sky-200 transition hover:bg-sky-500/30 disabled:cursor-not-allowed disabled:border-neutral-700 disabled:bg-neutral-800 disabled:text-neutral-500"
              >
                {isFiltering ? "RUNNING..." : "RUN"}
              </button>
            </aside>
          </div>
        </div>
      </div>

      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <button
          type="button"
          onClick={handleGenerateQuestions}
          disabled={isGenerating}
          className="rounded-lg border border-emerald-500 bg-emerald-500/20 px-4 py-2 text-sm font-semibold text-emerald-100 transition hover:bg-emerald-500/30 disabled:cursor-not-allowed disabled:border-neutral-700 disabled:bg-neutral-800 disabled:text-neutral-500"
        >
          {isGenerating ? "Generating..." : "Generate questions"}
        </button>

        <button
          type="button"
          className="rounded-lg border border-neutral-700 bg-neutral-950 px-5 py-2 text-sm font-bold tracking-wide text-neutral-100 transition hover:border-neutral-500"
        >
          SUBMIT
        </button>
      </div>
    </section>
  );
}
