import { randomUUID } from "crypto";
import { NextResponse } from "next/server";
import type { MapExtractionResult, MapGraphPayload } from "@/lib/map-types";

export const runtime = "nodejs";

function badRequest(message: string, status = 400) {
  return NextResponse.json({ error: message }, { status });
}

function buildPlaceholderGraph(): MapGraphPayload {
  // TODO(team-backend): replace this with real extraction output.
  // Expected response: vertices + edges + metadata.
  return {
    vertices: [
      { id: "B1", label: "B1", x: 0.78, y: 0.78, type: "Building" },
      { id: "B2", label: "B2", x: 0.68, y: 0.23, type: "Building" },
      { id: "B3", label: "B3", x: 0.46, y: 0.56, type: "Building" },
      { id: "B4", label: "B4", x: 0.2, y: 0.18, type: "Building" },
      { id: "T1", label: "T1", x: 0.6, y: 0.56, type: "Bin" },
    ],
    edges: [
      { id: "E1", source: "B4", target: "B2", label: "adjacent", weight: 20 },
      { id: "E2", source: "B2", target: "B3", label: "path", weight: 30 },
      { id: "E3", source: "B3", target: "T1", label: "transfer", weight: 12 },
    ],
    metadata: {
      coordinateSystem: "normalized",
      note: "Placeholder graph generated by map extraction stub.",
    },
  };
}

export async function POST(request: Request) {
  const formData = await request.formData();

  const componentId = String(formData.get("componentId") || "").trim();
  const overviewAdditionalInformation = String(formData.get("overviewAdditionalInformation") || "").trim();
  const binAdditionalInformation = String(formData.get("binAdditionalInformation") || "").trim();
  const overviewMapFiles = formData.getAll("overviewMapFiles").filter((entry): entry is File => entry instanceof File);
  const binLocationFiles = formData.getAll("binLocationFiles").filter((entry): entry is File => entry instanceof File);

  if (!componentId) {
    return badRequest("componentId is required.");
  }

  if (overviewMapFiles.length === 0) {
    return badRequest("At least one overview map image is required.");
  }

  try {
    const graph = buildPlaceholderGraph();

    const result: MapExtractionResult = {
      jobId: `map-extract-${randomUUID()}`,
      graph: {
        ...graph,
        metadata: {
          ...graph.metadata,
          componentId,
          overviewMapFileCount: overviewMapFiles.length,
          binLocationFileCount: binLocationFiles.length,
          overviewAdditionalInformation,
          binAdditionalInformation,
        },
      },
    };

    return NextResponse.json(result);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to extract map graph.";
    return badRequest(message, 500);
  }
}
