"""Auto-generated by the code-gen finalize_bundle stage.

Reads the metric contract that lives next to this file, samples the live
``Environment`` state per tick, and writes a JSON Lines metrics trace the
in-engine viewer (and downstream BI tools) can consume.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


class Reporter:
    """Tick-driven sampler that writes one JSONL row per metric sample.

    Schema of the log file (``metrics.jsonl``):

    First line is a header describing the run::

        {"_": "header", "run_id": "...", "started_at": "...",
         "tick_seconds": 300.0, "metrics": [{"name": ..., ...}, ...]}

    Subsequent lines are samples::

        {"t": 600.0, "metric": "queue_length",
         "entity_id": null, "value": 12.0}

    ``t`` is real-world seconds (tick_number * tick_seconds), so the
    log is self-describing regardless of the sim cadence.
    """

    def __init__(
        self,
        env: Any,
        *,
        run_id: str,
        out_dir: str | Path,
        tick_seconds: float = 300.0,
        contracts_path: str | Path = "metric_contracts.json",
    ) -> None:
        self.env = env
        self.run_id = run_id
        self.tick_seconds = float(tick_seconds)
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.log_path = self.out_dir / "metrics.jsonl"
        contracts = json.loads(Path(contracts_path).read_text(encoding="utf-8"))
        self.metrics: list[dict[str, Any]] = contracts.get("metrics", [])
        self._fp = self.log_path.open("w", encoding="utf-8")
        self._write_header()

    def _write_header(self) -> None:
        header = {
            "_": "header",
            "run_id": self.run_id,
            "started_at": datetime.now(timezone.utc).isoformat(),
            "tick_seconds": self.tick_seconds,
            "metrics": [
                {
                    "name": m.get("name"),
                    "label": m.get("label"),
                    "unit": m.get("unit", ""),
                    "agg": m.get("agg"),
                    "viz": m.get("viz"),
                    "chart_group": m.get("chart_group"),
                    "grounding": m.get("grounding"),
                }
                for m in self.metrics
            ],
        }
        self._fp.write(json.dumps(header, ensure_ascii=False) + "\n")
        self._fp.flush()

    # Best-effort matching: walk env.entities and return instances whose
    # class name equals or contains the requested entity kind. The codegen
    # entity stage generates one class per entity name so this is usually
    # exact.
    def _entity_instances_of(self, entity_kind: str) -> list[Any]:
        entities = getattr(self.env, "entities", None)
        if entities is None:
            return []
        try:
            iterable: Iterable[Any] = iter(entities)
        except TypeError:
            return []
        target = entity_kind.strip().lower()
        import re as _re
        # Strip non-word chars (e.g. Thai punctuation, dots) for fuzzy compare
        target_clean = _re.sub(r'[\W_]', '', target, flags=_re.UNICODE)
        out: list[Any] = []
        for inst in iterable:
            cls_name = type(inst).__name__.lower()
            # Strip the "entity_" prefix that codegen always prepends
            bare = cls_name[7:] if cls_name.startswith("entity_") else cls_name
            bare_clean = _re.sub(r'[\W_]', '', bare, flags=_re.UNICODE)
            if (cls_name == target or
                    target in cls_name or
                    bare in target or
                    (target_clean and bare_clean and
                     (bare_clean in target_clean or target_clean in bare_clean))):
                out.append(inst)
        return out

    def _read_attr(self, instance: Any, attr: str) -> float | None:
        try:
            value = getattr(instance, attr)
        except Exception:
            return None
        if value is None:
            return None
        if isinstance(value, bool):
            return 1.0 if value else 0.0
        if isinstance(value, (int, float)):
            return float(value)
        if isinstance(value, list):
            if not value:
                return 0.0
            if isinstance(value[0], (int, float)) and not isinstance(value[0], bool):
                return float(sum(float(x) for x in value if isinstance(x, (int, float))))
            if isinstance(value[0], dict):
                for key in ("weight", "amount", "value", "count", "quantity"):
                    vals = [v[key] for v in value if isinstance(v.get(key), (int, float))]
                    if vals:
                        return float(sum(vals))
            return float(len(value))
        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _aggregate(values: list[float], agg: str) -> float:
        if not values:
            return 0.0
        if agg == "sum":
            return float(sum(values))
        if agg == "max":
            return float(max(values))
        if agg == "min":
            return float(min(values))
        if agg == "count":
            return float(len(values))
        # mean / ratio / unknown -> mean
        return float(sum(values) / len(values))

    def _sample_metric(self, metric: dict[str, Any], t: float) -> None:
        agg = (metric.get("agg") or "mean").lower()
        deps = metric.get("required_attrs") or []
        if not deps:
            return

        # Special case: ratio over exactly two attrs -> sum(num) / sum(denom).
        if agg == "ratio" and len(deps) == 2:
            num_dep, den_dep = deps
            num_inst = self._entity_instances_of(str(num_dep.get("entity") or ""))
            den_inst = self._entity_instances_of(str(den_dep.get("entity") or ""))
            num_vals = [
                v
                for v in (self._read_attr(i, str(num_dep.get("attr") or "")) for i in num_inst)
                if v is not None
            ]
            den_vals = [
                v
                for v in (self._read_attr(i, str(den_dep.get("attr") or "")) for i in den_inst)
                if v is not None
            ]
            den_total = sum(den_vals)
            if not num_vals or den_total == 0:
                return
            value = float(sum(num_vals) / den_total)
            self._write_sample(t, metric.get("name"), None, value)
            return

        # Default case: aggregate across all required_attrs treated as one
        # pool of measurements. Common case is len(deps) == 1.
        pool: list[float] = []
        for dep in deps:
            ent_kind = str(dep.get("entity") or "")
            attr = str(dep.get("attr") or "")
            if not ent_kind or not attr:
                continue
            for inst in self._entity_instances_of(ent_kind):
                v = self._read_attr(inst, attr)
                if v is not None:
                    pool.append(v)

        # Fallback: if the exact required_attrs yielded nothing, scan all
        # numeric attrs on the matched entities. This handles the common case
        # where the AI-suggested attr name doesn't match the generated code.
        if not pool:
            seen: set = set()
            for dep in deps:
                ent_kind = str(dep.get("entity") or "")
                if not ent_kind:
                    continue
                for inst in self._entity_instances_of(ent_kind):
                    iid = id(inst)
                    if iid in seen:
                        continue
                    seen.add(iid)
                    for a in vars(inst):
                        if a.startswith("_"):
                            continue
                        v = self._read_attr(inst, a)
                        if v is not None:
                            pool.append(v)
                            break  # one attr per entity instance

        if not pool:
            return
        value = self._aggregate(pool, agg)
        self._write_sample(t, metric.get("name"), None, value)

    def _write_sample(
        self,
        t: float,
        metric_name: str | None,
        entity_id: str | None,
        value: float,
    ) -> None:
        row = {"t": t, "metric": metric_name, "entity_id": entity_id, "value": value}
        self._fp.write(json.dumps(row, ensure_ascii=False) + "\n")

    def sample(self, env: Any | None = None, tick_number: int = 0) -> None:
        if env is not None:
            self.env = env
        t = float(tick_number) * self.tick_seconds
        for metric in self.metrics:
            try:
                self._sample_metric(metric, t)
            except Exception:
                # Never let a sampling error kill the run.
                continue
        self._fp.flush()

    def close(self) -> None:
        try:
            self._fp.flush()
        finally:
            self._fp.close()
