"""Static templates emitted by ``finalize_bundle``.

These files are deterministic — they don't depend on any LLM call. Each
generated bundle gets:

- ``reporter.py`` reads ``metric_contracts.json`` and writes a JSON Lines
  trace at the configured ``tick_seconds`` cadence.
- ``run.py`` is the entrypoint: constructs ``Environment`` from the
  generated bundle, runs N ticks, hands each tick to the Reporter.
- ``metric_contracts.json`` — derived per-run from the user's
  ``selectedMetrics`` (frozen at job submission time).
- ``pbi/recipe.json`` — chart-group → visual mapping the in-engine
  viewer and any future PowerBI report can both consume.
- ``pbi/theme.json`` — a small static color theme so the viewer and
  PowerBI render with consistent palette.
- ``runs/`` is the conventional output directory the Reporter writes
  ``metrics.jsonl`` into.
"""

from __future__ import annotations

import json
from typing import Any


REPORTER_PY = '''"""Auto-generated by the code-gen finalize_bundle stage.

Reads the metric contract that lives next to this file, samples the live
``Environment`` state per tick, and writes a JSON Lines metrics trace the
in-engine viewer (and downstream BI tools) can consume.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


class Reporter:
    """Tick-driven sampler that writes one JSONL row per metric sample.

    Schema of the log file (``metrics.jsonl``):

    First line is a header describing the run::

        {"_": "header", "run_id": "...", "started_at": "...",
         "tick_seconds": 300.0, "metrics": [{"name": ..., ...}, ...]}

    Subsequent lines are samples::

        {"t": 600.0, "metric": "queue_length",
         "entity_id": null, "value": 12.0}

    ``t`` is real-world seconds (tick_number * tick_seconds), so the
    log is self-describing regardless of the sim cadence.
    """

    def __init__(
        self,
        env: Any,
        *,
        run_id: str,
        out_dir: str | Path,
        tick_seconds: float = 300.0,
        contracts_path: str | Path = "metric_contracts.json",
    ) -> None:
        self.env = env
        self.run_id = run_id
        self.tick_seconds = float(tick_seconds)
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.log_path = self.out_dir / "metrics.jsonl"
        contracts = json.loads(Path(contracts_path).read_text(encoding="utf-8"))
        self.metrics: list[dict[str, Any]] = contracts.get("metrics", [])
        self._fp = self.log_path.open("w", encoding="utf-8")
        self._write_header()

    def _write_header(self) -> None:
        header = {
            "_": "header",
            "run_id": self.run_id,
            "started_at": datetime.now(timezone.utc).isoformat(),
            "tick_seconds": self.tick_seconds,
            "metrics": [
                {
                    "name": m.get("name"),
                    "label": m.get("label"),
                    "unit": m.get("unit", ""),
                    "agg": m.get("agg"),
                    "viz": m.get("viz"),
                    "chart_group": m.get("chart_group"),
                    "grounding": m.get("grounding"),
                }
                for m in self.metrics
            ],
        }
        self._fp.write(json.dumps(header, ensure_ascii=False) + "\\n")
        self._fp.flush()

    # Best-effort matching: walk env.entities and return instances whose
    # class name equals or contains the requested entity kind. The codegen
    # entity stage generates one class per entity name so this is usually
    # exact.
    def _entity_instances_of(self, entity_kind: str) -> list[Any]:
        entities = getattr(self.env, "entities", None)
        if entities is None:
            return []
        try:
            iterable: Iterable[Any] = iter(entities)
        except TypeError:
            return []
        target = entity_kind.strip().lower()
        out: list[Any] = []
        for inst in iterable:
            cls_name = type(inst).__name__.lower()
            if cls_name == target or target in cls_name:
                out.append(inst)
        return out

    def _read_attr(self, instance: Any, attr: str) -> float | None:
        try:
            value = getattr(instance, attr)
        except Exception:
            return None
        if value is None:
            return None
        if isinstance(value, bool):
            return 1.0 if value else 0.0
        if isinstance(value, (int, float)):
            return float(value)
        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _aggregate(values: list[float], agg: str) -> float:
        if not values:
            return 0.0
        if agg == "sum":
            return float(sum(values))
        if agg == "max":
            return float(max(values))
        if agg == "min":
            return float(min(values))
        if agg == "count":
            return float(len(values))
        # mean / ratio / unknown -> mean
        return float(sum(values) / len(values))

    def _sample_metric(self, metric: dict[str, Any], t: float) -> None:
        agg = (metric.get("agg") or "mean").lower()
        deps = metric.get("required_attrs") or []
        if not deps:
            return

        # Special case: ratio over exactly two attrs -> sum(num) / sum(denom).
        if agg == "ratio" and len(deps) == 2:
            num_dep, den_dep = deps
            num_inst = self._entity_instances_of(str(num_dep.get("entity") or ""))
            den_inst = self._entity_instances_of(str(den_dep.get("entity") or ""))
            num_vals = [
                v
                for v in (self._read_attr(i, str(num_dep.get("attr") or "")) for i in num_inst)
                if v is not None
            ]
            den_vals = [
                v
                for v in (self._read_attr(i, str(den_dep.get("attr") or "")) for i in den_inst)
                if v is not None
            ]
            den_total = sum(den_vals)
            if not num_vals or den_total == 0:
                return
            value = float(sum(num_vals) / den_total)
            self._write_sample(t, metric.get("name"), None, value)
            return

        # Default case: aggregate across all required_attrs treated as one
        # pool of measurements. Common case is len(deps) == 1.
        pool: list[float] = []
        for dep in deps:
            ent_kind = str(dep.get("entity") or "")
            attr = str(dep.get("attr") or "")
            if not ent_kind or not attr:
                continue
            for inst in self._entity_instances_of(ent_kind):
                v = self._read_attr(inst, attr)
                if v is not None:
                    pool.append(v)
        if not pool:
            return
        value = self._aggregate(pool, agg)
        self._write_sample(t, metric.get("name"), None, value)

    def _write_sample(
        self,
        t: float,
        metric_name: str | None,
        entity_id: str | None,
        value: float,
    ) -> None:
        row = {"t": t, "metric": metric_name, "entity_id": entity_id, "value": value}
        self._fp.write(json.dumps(row, ensure_ascii=False) + "\\n")

    def sample(self, env: Any | None = None, tick_number: int = 0) -> None:
        if env is not None:
            self.env = env
        t = float(tick_number) * self.tick_seconds
        for metric in self.metrics:
            if (metric.get("sampling_event") or "tick") != "tick":
                continue
            try:
                self._sample_metric(metric, t)
            except Exception:
                # Never let a sampling error kill the run.
                continue
        self._fp.flush()

    def close(self) -> None:
        try:
            self._fp.flush()
        finally:
            self._fp.close()
'''


RUN_PY = '''"""Entrypoint for the generated simulation bundle.

Constructs the Environment, runs N ticks, hands each tick to the Reporter
which writes a JSONL metrics trace under ``runs/<run_id>/metrics.jsonl``.

Usage::

    python run.py --ticks 100 --tick-seconds 300

The Reporter and metric contract files live next to this script.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from datetime import datetime, timezone
from pathlib import Path

from environment import Environment
from reporter import Reporter


def _load_entities() -> list:
    """Dynamically import and instantiate all entity classes from entities/ directory."""
    entities = []
    entities_dir = Path(__file__).resolve().parent / "entities"
    
    if not entities_dir.exists():
        return entities
    
    for entity_file in sorted(entities_dir.glob("*.py")):
        if entity_file.name.startswith("_"):
            continue
        
        try:
            # Load module dynamically
            spec = importlib.util.spec_from_file_location(entity_file.stem, entity_file)
            if spec is None or spec.loader is None:
                continue
            module = importlib.util.module_from_spec(spec)
            sys.modules[entity_file.stem] = module
            spec.loader.exec_module(module)
            
            # Find the entity class (first class that starts with Entity_)
            for attr_name in dir(module):
                if attr_name.startswith("Entity_"):
                    entity_class = getattr(module, attr_name)
                    if isinstance(entity_class, type):
                        # Instantiate entity with no args (or minimal default args)
                        try:
                            entity_instance = entity_class()
                            entities.append(entity_instance)
                        except Exception as e:
                            print(f"warning: failed to instantiate {attr_name}: {e}")
        except Exception as e:
            print(f"warning: failed to load entity {entity_file.stem}: {e}")
    
    return entities


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ticks", type=int, default=100)
    parser.add_argument("--tick-seconds", type=float, default=300.0)
    parser.add_argument("--out", type=str, default=None)
    parser.add_argument("--run-id", type=str, default=None)
    args = parser.parse_args()

    run_id = args.run_id or datetime.now(timezone.utc).strftime("run-%Y%m%dT%H%M%SZ")
    here = Path(__file__).resolve().parent
    out_dir = Path(args.out) if args.out else here / "runs" / run_id

    contracts_path = here / "metric_contracts.json"
    if not contracts_path.exists():
        print(f"metric_contracts.json not found at {contracts_path}; aborting.")
        return 2

    # Load and instantiate all entities
    entities = _load_entities()
    
    # Pass entities to Environment constructor
    env = Environment(entities=entities)
    reporter = Reporter(
        env=env,
        run_id=run_id,
        out_dir=out_dir,
        tick_seconds=args.tick_seconds,
        contracts_path=str(contracts_path),
    )

    try:
        for tick in range(args.ticks):
            try:
                env.tick(args.tick_seconds)
            except TypeError:
                env.tick()
            reporter.sample(env=env, tick_number=tick + 1)
    finally:
        reporter.close()

    print(f"run complete: {reporter.log_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


PBI_THEME_JSON: dict[str, Any] = {
    "name": "GMSE Default",
    "dataColors": [
        "#38bdf8",
        "#a855f7",
        "#34d399",
        "#f59e0b",
        "#f472b6",
        "#22d3ee",
        "#fb7185",
        "#facc15",
    ],
    "background": "#0a0a0a",
    "foreground": "#e5e5e5",
    "tableAccent": "#38bdf8",
}


def build_metric_contracts(
    selected_metrics: list[dict[str, Any]],
    *,
    job_id: str,
) -> dict[str, Any]:
    return {
        "schemaVersion": 1,
        "jobId": job_id,
        "metrics": [dict(m) for m in selected_metrics if isinstance(m, dict)],
    }


def build_pbi_recipe(
    selected_metrics: list[dict[str, Any]],
    *,
    job_id: str,
) -> dict[str, Any]:
    """Group metrics by ``chart_group``; emit one panel per group."""
    panels: list[dict[str, Any]] = []
    by_group: dict[str, list[dict[str, Any]]] = {}
    ungrouped: list[dict[str, Any]] = []
    for m in selected_metrics:
        if not isinstance(m, dict):
            continue
        group = m.get("chart_group")
        if isinstance(group, str) and group.strip():
            by_group.setdefault(group.strip(), []).append(m)
        else:
            ungrouped.append(m)

    for group_name, members in by_group.items():
        # All members of a chart group share the first member's viz to
        # simplify visualization. The viewer can override per chart panel.
        viz = next((m.get("viz") for m in members if m.get("viz")), "line")
        panels.append(
            {
                "chart_group": group_name,
                "visual": viz,
                "y_metrics": [m.get("name") for m in members],
                "shared_x": "tick_seconds",
                "slicers": ["entity_kind", "grounding"],
            }
        )

    for m in ungrouped:
        panels.append(
            {
                "chart_group": None,
                "visual": m.get("viz") or "line",
                "y_metrics": [m.get("name")],
                "shared_x": "tick_seconds",
                "slicers": ["entity_kind", "grounding"],
            }
        )

    return {
        "schemaVersion": 1,
        "jobId": job_id,
        "panels": panels,
    }


def serialize_json(payload: Any) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2)
